server:
  port: 8080
  servlet:
    context-path: /api
# 数据库配置
spring:
#  可以指定环境
#  profiles:
#    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuhaigui?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
# 接口文档
knife4j:
  enable: true
  openapi:
    title: 鱼皮的接口文档
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.yupi.yuhaigui.controller
# 接入 AI 大模型
ai:
  apiKey: 填写你自己的 API Key